services:
  shelfie:
    build:
      context: .
      dockerfile: Shelfie/Dockerfile
    image: shelfie
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:8080:8080"
